### ISSUE TITLE
Displaying file statistics

### ISSUE THREAD

**Issue by folkertdev** [RUGSoftEng/2017-Web-Service-Author-Analysis#13]
I've just pushed the code that will expose some statistics of the documents during the processing in the other repo. 

the next steps will be

* getting the data to the frontend
    I'd like the webserver to not depend on the exact shape of the json. This is the default with normal js, but I'm not sure how typescript handles this. Ideally, the server would accept a string from the backend and give a string to the frontend (reason: one fewer place to change stuff when we want to send more/other values)
* finding interesting data to display (and document what these values mean)
* properly display the data
    my current idea is to use [elm-plot](https://terezka.github.io/elm-plot/) for this. 

example json

```json
{
	"unknown": {
		"blocks": 13,
		"lineEndings": {
			",": 18,
			"?": 3,
			";": 8,
			".": 6,
			"!": 13,
			" ": 0,
			"-": 2
		},
		"lines": 74,
		"punctuation": {
			",": 35,
			"?": 3,
			";": 8,
			"'": 13,
			":": 2,
			"!": 13,
			".": 6,
			"-": 9
		},
		"sentencesFull": 23,
		"words": 445,
		"blockChars": 3019,
		"blank_lines": 0,
		"sentences": 60,
		"blockLines": 62,
		"characters": 3043,
		"lowers": 1555,
		"uppers": 74
	},
	"known": {
		"blocks": 17,
		"lineEndings": {
			",": 1,
			"?": 9,
			";": 0,
			".": 8,
			"!": 0,
			" ": 0,
			"-": 0
		},
		"lines": 52,
		"punctuation": {
			".": 22,
			"!": 1,
			"-": 0,
			",": 26,
			"?": 11,
			";": 3,
			"'": 21,
			":": 0
		},
		"sentencesFull": 34,
		"words": 405,
		"blockChars": 1667,
		"blank_lines": 0,
		"sentences": 52,
		"blockLines": 36,
		"characters": 1699,
		"lowers": 1193,
		"uppers": 84
	}
}
```

**Comment by dennis-school** [comment]
You want the JSON data to be moved from GLAD - through the webserver - to the frontend, without internal modification?

To clarify TypeScript + JSON: TypeScript does not care about the shape of JSON. Just like JavaScript.

And what about multiple known-author files for this output? Is that possible? Or are these texts contatenated at the input stage?

**Comment by folkertdev** [comment]
yes. just transferring the data from the backend to the frontend. 

the features for the known author files are all combined into one set of features (e.g. total number of capital letters divided by total number of characters).

**Comment by folkertdev** [comment]
We have some new fields, @LuigiGao or @DspatieJ could you extend our decoders and model to store it, and get it to display in a plot. We added 

```json
"similarities": {"punctuation": 0.7939441422400348, "line_endings": 0.31265847737995733, "line_length": 0.9999799859581755, "letter_case": 0.04794504524294862, "text_block": 136.8235294117647}
```
